WebBanHangOnline/Models/EF/ProductCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebBanHangOnline.Models.EF
{
    [Table("tb_ProductCategory")]
    public class ProductCategory : CommonAbstract
    {
        public ProductCategory()
        {
            this.products = new HashSet<Product>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Title { get; set; }
        [Required]
        [StringLength(150)]
        public string Alias { get; set; }
        public string Description { get; set; }
        [StringLength(250)]
        public string Icon { get; set; }
        [StringLength(250)]
        public string SeoTitle { get; set; }
        [StringLength(500)]
        public string SeoDescription { get; set; }
        [StringLength(250)]
        public string SeoKeywords { get; set; }
        public ICollection<Product> products { get; set; }
    }
}

WebBanHangOnline/Areas/Admin/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHangOnline.Models;
using WebBanHangOnline.Models.EF;

namespace WebBanHangOnline.Areas.Admin.Controllers
{
    public class ProductCategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/ProductCategory
        public ActionResult Index()
        {
            var items = db.ProductCategories.ToList();
            return View(items);
        }

        public ActionResult Add()
        {
            ProductCategory category = new ProductCategory();
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ProductCategory model)
        {
            if(ModelState.IsValid)
            {
                model.CreatedDate = DateTime.Now;
                model.ModifierDate = DateTime.Now;
                model.Alias = WebBanHangOnline.Models.Common.Fillter.FilterChar(model.Title);
                db.ProductCategories.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }

    
}

WebBanHangOnline/Controllers/NewsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHangOnline.Models;
using WebBanHangOnline.Models.EF;

namespace WebBanHangOnline.Controllers
{
    public class NewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: News
        public ActionResult Index(int? page)
        {
            var pageSize = 10;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<New> items = db.News.OrderByDescending(x => x.CreatedDate).ToList();
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }

        public ActionResult Partial_News_Home()
        {
            var items = db.News.Take(3).ToList();
            return PartialView(items);
        }

        public ActionResult Detail(int id)
        {
            var item = db.News.Find(id);
            return View(item);
        }
    }
}

WebBanHangOnline/Areas/Admin/Views/ProductCategory/Add.cshtml
@model WebBanHangOnline.Models.EF.ProductCategory
@{
    ViewBag.Title = "Thêm mới danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader {
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Home" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Thêm mới</a>
        </li>
    </ul>
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thêm mới danh mục sản phẩm</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Danh mục sản phẩm</a></li>
                    <li class="breadcrumb-item active">Thêm mới</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông tin thêm mới danh mục sản phẩm</h3>
        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Add", "ProductCategory", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <!-- your steps content here -->
                <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tên danh mục</label>
                        @Html.TextBoxFor(x => x.Title, new
                        {
                            @class = "form-control",
                            @placeholder = "Tên danh mục"
                        })
                        @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Alias</label>
                        @Html.TextBoxFor(x => x.Alias, new
                        {
                            @class = "form-control",
                            @placeholder = "Alias"
                        })
                        @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Mô tả</label>
                        @Html.TextAreaFor(x => x.Description, new
                        {
                           @class = "form-control",
                           @placeholder = "Mô tả"
                       })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Title</label>
                        @Html.TextBoxFor(x => x.SeoTitle, new
                        {
                           @class = "form-control",
                           @placeholder = "SEO Title"
                        })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Description</label>
                        @Html.TextAreaFor(x => x.SeoDescription, new
                        {
                           @class = "form-control",
                           @placeholder = "SEO Description"
                        })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Keyword</label>
                        @Html.TextBoxFor(x => x.SeoKeywords, new
                        {
                           @class = "form-control",
                           @placeholder = "SEO Keyword"
                        })
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Lưu</button>
                        <a href="/admin/ProductCategory" class="btn btn-danger">Quay lại</a>
                    </div>
                </div>
                }
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->

WebBanHangOnline/Areas/Admin/Views/ProductCategory/Index.cshtml
@model IEnumerable<WebBanHangOnline.Models.EF.ProductCategory>
@{
    ViewBag.Title = "Danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using PagedList.Mvc;
@using PagedList;

@section naviheader {
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Home" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/ProductCategory" class="nav-link">@ViewBag.Title</a>
        </li>
    </ul>
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản lý danh mục sản phẩm</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách danh mục sản phẩm</h3>

            <div class="card-tools">
                <a href="/admin/ProductCategory/add" class="btn btn-primary">Thêm mới</a>
                <a href="#" class="btn btn-danger" id="btnDeleteAll">Xóa</a>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                @*<div class="col-6">
                    @using (Html.BeginForm("index", "News", FormMethod.Get, new { }))
                    {
                        <div class="input-group input-group-sm">
                            @Html.TextBox("SearchText", new
                            {
                               @class = "form-control"
                            })
                            <span class="input-group-append">
                                <button type="submit" class="btn btn-info btn-flat">Tìm kiếm</button>
                            </span>
                        </div>
                    }
                </div>*@
            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="selectAll" /></th>
                        <th>STT</th>
                        <th>Tiêu đề</th>
                        <th>Ngày tạo</th>
                        <th>Hiển thị</th>
                        <th style="width:150px"></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = 1;
                        foreach (var item in Model)
                        {
                            //var strCheck = item.IsActive ? "<i class='fa fa-check text-success'></i>" : "<i class='fa fa-times text-danger'></i>";
                            <tr id="trow_@item.Id">
                                <td><input type="checkbox" class="cbkItem" value="@item.Id" /></td>
                                <td>@i</td>
                                <td>@item.Title</td>
                                <td>@item.CreatedDate.ToString("dd/MM/yyyy")</td>
                                @*<td class="text-center">
                                    <a href='#' data-id="@item.Id" class="btnActive">@Html.Raw(strCheck)</a>
                                </td>*@
                                <td>
                                    <a href="/admin/ProductCategory/edit/@item.Id" class="btn btn-warning">Sửa</a>
                                    <a data-id="@item.Id" class="btn btn-danger btnDelete">Xóa</a>
                                </td>
                            </tr>
                            i++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">Không có bản ghi nào!</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>

@section scripts {
    <script>
        $(document).ready(function () {
            $('body').on('click', '#btnDeleteAll', function (e) {
                e.preventDefault();
                var str = "";
                var checkbox = $(this).parents('.card').find('tr td input:checkbox');
                var i = 0;
                checkbox.each(function () {
                    if (this.checked) {
                        checkbox.attr('selected', 'checked')
                        var _id = $(this).val();
                        if (i === 0) {
                            str += _id;
                        } else {
                            str += "," + _id;
                        }
                        i++;
                    } else {
                        checkbox.attr('selected', '');
                    }
                });

                if (str.length > 0) {
                    var conf = confirm("Bạn có muốn xóa các bản ghi này hay không?");
                    if (conf === true) {
                        $.ajax({
                            url: '/admin/news/DeleteAll',
                            type: 'POST',
                            data: { ids: str },
                            success: function (rs) {
                                if (rs.success) {
                                    location.reload();
                                }
                            }
                        });
                    }
                }
            });

            $('body').on('change', '#selectAll', function () {
                var checkStatus = this.checked;
                var checkbox = $(this).parents('.card-body').find('tr td input:checkbox');
                checkbox.each(function () {
                    this.checked = checkStatus;
                    if (this.checked) {
                        checkbox.attr('selected', 'checked')
                    } else {
                        checkbox.attr('selected', '')
                    }
                });
            });

            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                var conf = confirm("Bạn có muốn xóa bản ghi này không?")
                if (conf == true) {
                    $.ajax({
                        url: '/admin/News/Delete',
                        type: "POST",
                        data: { id: id },
                        success: function (res) {
                            if (res.success == true) {
                                $("#trow_" + id).remove();
                            } else {
                                alert("Xóa không thành công")
                            }
                        }
                    });
                }
            })

            $('body').on('click', '.btnActive', function (e) {
                e.preventDefault();
                var btn = $(this);
                var id = btn.data("id");
                $.ajax({
                    url: '/admin/News/IsActive',
                    type: "POST",
                    data: { id: id },
                    success: function (res) {
                        if (res.success) {
                            if (res.isActive == true) {
                                btn.html("<i class='fa fa-check text-success'></i>");
                            } else {
                                btn.html("<i class='fa fa-times text-danger'></i>");
                            }
                        }
                        else {
                            alert("Đổi trạng thái không thành công")
                        }
                    }
                });
            })

        })
    </script>
}